### PR TITLE
Added dot and s vim commands

### PR DESCRIPTION
**Pull request by JoshBrudnak**

### CODE REVIEW

**Comment by bpowell** [comment]
@JoshBrudnak when using the `s` command, it doesn't tell you that you are in INSERT mode. The `.` operator seems to be working as expected

**Comment by JoshBrudnak** [comment]
@bpowell I added the insert message :+1:

**Comment by JoshBrudnak** [comment]
I'll also update the readme with the new commands.

**Comment by bpowell** [comment]
When entering insert mode from any command, I have to hit `ESC` twice to get out of insert mode.

**Pull request merged**
